version: '3.8'

services:
  pythontelegrambottemplate:
    image: ghcr.io/shchavr/telegram-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "${Europe/Moscow}"  
      BOT_TOKEN: "${BOT_TOKEN}"  
      PYTHONPATH: "${PYTHONPATH}"  

    env_file:
      - .env  
    volumes:
      - ./data:/app/data  
    restart: unless-stopped
